### PR TITLE
Added dive list into table

### PR DESCRIPTION
**Pull request by taratip**
I've put data from word table onto Dive List 2017 page. You can edit data in js/dive-list.js file.

### CODE REVIEW

**Comment by taratip** [comment]
This is for issue#60

**Comment by monroemann** [comment]
Tara!  That is gorgeous!  And it's broken down into pages as well!  So impressive!  

What is the name of the js file that we would update to edit the table?

If we had to re-number the dives, is there an easy way to do that, or just manually change each one?  Fortunately, there are only about 120 of them, but if the table grows, that might be tedious in the future.  Not a big deal for now--just curious. 😄

**Comment by monroemann** [comment]
Tara, I broke something :(  The files apparently are still there, but I don't see the table displaying anymore.  What did I do?  I hope you can easily fix it.

**Comment by taratip** [comment]
It seems data was not properly created or changed. Did you change something in dive-list js file? perhaps, some data in dataSet variable?

**Comment by taratip** [comment]
Never mind. I found it. Looked like you changed the order of the data. You forgot to put ',' at the end of the last row of moved data and you didn't remove ',' at the very last row of all data.

**Comment by monroemann** [comment]
Ahh, yes. That makes sense. I moved the last three entries in order to put them in proper alphabetical order. 

Now I know that if I move the last entry or add a new entry at bottom, the commas are key. 

Thank you!

**Pull request merged**
