### PR TITLE
Created the new Gold Ambitions program page and others

### PR DESCRIPTION
**Pull request by chalupavigilante**
I created the new Gold Ambitions page and the pages these link to. Anything I couldn't find a specific Slack chat group on, I put # as a placeholder in the link. Please review. Thanks!

### CODE REVIEW

**Comment by monroemann** [comment]
I am going to merge this, and create the nav link myself.  Great work Roberto!  You're getting the hang of it.  Fun, isn't it? haha

**Comment by monroemann** [comment]
You can delete the branch now

**Comment by monroemann** [comment]
I stand corrected!  You DID adjust the navigation.html file.  Or was it already there?  In any case, GREAT WORK!

**Comment by chalupavigilante** [comment]
Yes Monroe, I even adjusted the navigation.html file before submitting it to you. :)

**Pull request merged**
