### PR TITLE
Added nav bar and footer to french_chat page

### PR DESCRIPTION
**Pull request by taratip**
I have added the nav bar and footer to french_chat page. I didn't edit at first because I wasn't sure if we still use this page. We'll need to change other chat pages as well.

### CODE REVIEW

**Comment by monroemann** [comment]
Did you get rid of the bootstrap button for people to join, or is it still there?

Also, how can I view what the page looks like without merging it?  Can I?

**Comment by taratip** [comment]
The button is still there but it directed to different slack group (not french channel). You can view without merging by cloning this branch to your computer. Use `git clone -b <current-remote-branch> --single-branch https://github.com/monroemann/breakdivingnew.git`

**Comment by monroemann** [comment]
Which Slack group did it direct people to?  The link should just go to the basic 'join slack' page..

**Comment by monroemann** [comment]
Yes, we still use these pages.  These are the ones the google searchers come to when they click on the specific adwords ad for that particular topic.

What's the best way to change all the pages?  Delete all the nav bar code, and then add the jquery code to replace it?

**Comment by taratip** [comment]
I already changed all chat landing pages

**Pull request merged**
