### PR TITLE
set all links to join the slack community to open into a new window

### PR DESCRIPTION
**Pull request by taratip**
All links to join the community now open into a new window instead of same window.

### CODE REVIEW

**Comment by taratip** [comment]
Made the changes based on feedback

**Comment by monroemann** [comment]
Whoops, I think based on something Chomba worked on, now there is a merge conflict with two files: photo_credit.html and publicity.html.  I believe chomba changed the name of the publicity page on my request to news_and_publicity.html.  I am not sure about the photo_credit.html conflict.  

Do either of you know how I can best resolve this?

**Comment by monroemann** [comment]
Thank you, Tara, for your help. :)

**Comment by chmb** [comment]
You could copy the changes you have made to a separate location, stash the
changes and then merge and then add the changes after you have merged.

**Comment by chmb** [comment]
The photo credit conflict is because I normalized the headers in that file.

**Comment by monroemann** [comment]
It's weird.  I see Chomba's comments in Slack, but not here on this message board.  

Anyway, I already merged Chomba's changes.  The question is how to now accept Tara's...

**Comment by monroemann** [comment]
I'm exhausted.  Maybe you guys can help me figure this out:

https://gyazo.com/315e14ceae8d150cc8bbb3d331c37f6f

I've made all the changes, but it still says there are merges to make.  I don't know how to do that :D

**Comment by taratip** [comment]
I've merged the conflict in photo_credit.html.

**Pull request merged**
